version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm
      - run:
          name: Install project dependencies
          command: pnpm install
      - save_cache:
          key: pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.local/share/pnpm/store/v3
      - run:
          name: Run linting
          command: pnpm lint
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm
      - run:
          name: Install project dependencies
          command: pnpm install
      - save_cache:
          key: pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.local/share/pnpm/store/v3
      - run:
          name: Build project
          command: pnpm build
workflows:
  lint_and_build:
    jobs:
      - lint
      - build:
          requires:
            - lint
